; [Unit]
; After=wayland-session@hyprland.desktop.target
;
; [Service]
; Slice=session-graphical.slice
; ExecCondition=/lib/systemd/systemd-xdg-autostart-condition "wlroots:sway:Wayfire:labwc:Hyprland" ""
;
; [Install]
; WantedBy=wayland-session@hyprland.desktop.target
