Include = /etc/paru.conf

[options]
BottomUp
SudoLoop
SaveChanges
CombinedUpgrade
UpgradeMenu
NewsOnUpgrade
PacmanConf = /home/jalhamer/.config/pacman/pacman.conf

[bin]
FileManager = /usr/bin/yazi
Bat = /usr/bin/bat
Pager = /usr/bin/less
