log_level        = "warn,ashell::services::tray=debug"
outputs          = "All"
position         = "Top"
enable_esc_key   = true
app_launcher_cmd = "nc -U /run/user/1000/walker/walker.sock"
clipboard_cmd    = "walker -m clipboard"

[modules]
  left = [
    [
      "AppLauncher",
      "Clipboard",
      "Updates",
      "Workspaces",
      "WindowTitle",
      "Tray",
      "MediaPlayer",
    ],
  ]
  center = [
    [
      "ToggleNotifications",
      "PopNotification",
      "RemoveNotification",
      "ClearNotificationHistory",
    ],
  ]
  right = [["KeyboardSubmap", "Privacy", "Settings", "SystemInfo", "Clock"]]

[updates]
  check_cmd  = "checkupdates; paru -Qua"
  update_cmd = "kitty -- zsh -c 'paru; echo Done - Press enter to exit; read' &"

[workspaces]
  workspace_names          = ["󰽤", "󰽧", "󰽡", "󰽨", "󰽢", "󰽦", "󰽣", "󰽥"]
  max_workspaces           = 8
  enable_workspace_filling = true

[window_title]
  mode                        = "Title" # or "Class"
  truncate_title_after_length = 75

[media_player]
  max_title_length = 75

[system_info]
  indicators = ["Temperature", "Cpu", "Memory"]

  [system_info.temperature]
    sensor = "system76_acpi CPU temp"

[clock]
  format = "  %A, %Y-%m-%d   %H:%M:%S:%z"

[settings]
  lock_cmd      = "loginctl lock-session"
  shutdown_cmd  = "systemctl poweroff"
  suspend_cmd   = "systemctl suspend"
  hibernate_cmd = "systemctl hibernate"
  reboot_cmd    = "systemctl reboot"
  logout_cmd    = "uwsm stop"

  audio_sinks_more_cmd   = "app2unit -- pavucontrol -t 3"
  audio_sources_more_cmd = "app2unit -- pavucontrol -t 4"
  wifi_more_cmd          = "app2unit-term -- impala"
  bluetooth_more_cmd     = "app2unit-term -- bluetui"
  vpn_more_cmd           = "app2unit -- mullvad-vpn"

  battery_format            = "Icon"
  peripheral_battery_format = "IconAndPercentage"

[[CustomModule]]
  name                = "ToggleNotifications"
  icon                = ""
  command             = "sleep 0.1 && dunstctl set-paused toggle"
  listen_cmd          = "python ~/.config/ashell/scripts/ToggleNotifications/listen_cmd.py"
  icons.'dnd.*'       = ""
  icons.'email.*'     = ""
  icons.'chat.*'      = "󱋊"
  icons.'system.*'    = "󱨪"
  icons.'network.*'   = "󱂇"
  icons.'battery.*'   = "󰁺"
  icons.'update.*'    = "󰚰"
  icons.'music.*'     = "󰝚"
  icons.'volume.*'    = "󰕿"
  icons.'hypr.*'      = ""
  icons.'mpv.*'       = ""
  icons.'display.*'   = "󰍹"
  icons.'security.*'  = "󰒃"
  icons.'timecheck.*' = "󰾨"
  alert               = ".*notification"

[[CustomModule]]
  name    = "PopNotification"
  icon    = "󰪒"
  command = "sleep 0.1 && dunstctl history-pop"

[[CustomModule]]
  name    = "RemoveNotification"
  icon    = "󱏪"
  command = "python ~/.config/ashell/scripts/RemoveNotification/command.py"

[[CustomModule]]
  name    = "ClearNotificationHistory"
  icon    = "󱏬"
  command = "dunstctl history-clear"

[appearance]
  font_name    = "VictorMono Nerd Font"
  style        = "Solid"
  scale_factor = 1.25
  opacity      = 0.9

  success_color = "#a6da95"
  text_color    = "#cad3f5"

  workspace_colors         = ["#eed49f", "#f5bde6"]
  special_workspace_colors = ["#c6a0f6", "#8aadf4"]

  [appearance.primary_color]
    base   = "#7dc4e4"
    weak   = "#f0c6c6"
    strong = "#8aadf4"
    text   = "#181926"

  [appearance.danger_color]
    base = "#ed8796"
    weak = "#f5a97f"

  [appearance.background_color]
    base   = "#24273a"
    weak   = "#363a4f"
    strong = "#494d64"

  [appearance.secondary_color]
    base   = "#f0c6c6"
    strong = "#1e2030"
    weak   = "#363a4f"
    text   = "#181926"

  [appearance.menu]
    opacity  = 0.9
    backdrop = 0.2
